# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseReportSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('impulse', models.CharField(blank=True, choices=[('IP', 'IP'), ('eP', 'eP')], default='IP', max_length=2)),
                ('p_arrival', models.TimeField(blank=True)),
                ('s_arrival', models.TimeField(blank=True)),
                ('first_motion', models.CharField(blank=True, choices=[('CNE', 'CNE'), ('CNW', 'CNW'), ('CSE', 'CSE'), ('CSW', 'CSW'), ('DNE', 'DNE'), ('DNW', ' DNW'), ('DSE', 'DSE'), ('DSW', 'DSW')], default='CNE', max_length=3)),
                ('komponen_Z', models.FloatField(blank=True)),
                ('komponen_NS', models.FloatField(blank=True)),
                ('komponen_EW', models.FloatField(blank=True)),
                ('a_maksimum', models.FloatField(blank=True)),
                ('Periode', models.FloatField(blank=True)),
                ('Tipe', models.CharField(blank=True, choices=[('local', 'local'), ('Tele', 'Tele')], default='local', max_length=2)),
                ('Distance', models.FloatField(blank=True)),
                ('magnitudo_durasi', models.FloatField(blank=True)),
                ('origin_time', models.TimeField()),
                ('lintang', models.FloatField(default=0.0)),
                ('bujur', models.FloatField(default=0.0)),
                ('kedalaman', models.IntegerField(default=10)),
                ('magnitudo', models.FloatField(default=0.0)),
                ('tipe_magnitudo', models.CharField(choices=[('M', 'M'), ('MSH', 'MSH'), ('Mw', 'Mw'), ('Mwp', 'Mwp'), ('Ms', 'Ms'), ('MLv', 'MLv')], default='M', max_length=5)),
                ('dirasakan', models.CharField(blank=True, choices=[('Tidak Dirasakan', 'Tidak Dirasakan'), ('Dirasakan', 'Dirasakan')], default='Tidak Dirasakan', max_length=50)),
                ('Sekala_MMI', models.CharField(blank=True, help_text='Jika Gempa Dirasakan', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tanggal'],
            },
        ),
    ]
