# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasereportsheet',
            name='inisial',
        ),
    ]
