# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasereportsheet',
            old_name='Sekala_MMI',
            new_name='sekala_mmi',
        ),
    ]
