# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthqs', '0002_auto_20160512_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phasereportsheet',
            old_name='sekala_mmi',
            new_name='skala_mmi',
        ),
    ]
